name: Build

on:
  workflow_call:

jobs:
  build-appimage:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libexiv2-dev libgl1-mesa-dev file
          
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.0'
          modules: 'qtwayland'
          
      - name: Build Sura
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build
          
      - name: Build AppImage
        run: |
          # Download linuxdeployqt
          wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
          chmod a+x linuxdeployqt-continuous-x86_64.AppImage
          
          # Prepare AppDir
          mkdir -p AppDir/usr/bin AppDir/usr/share/applications AppDir/usr/share/icons/hicolor/256x256/apps
          cp build/Sura AppDir/usr/bin/sura
          cp resources/images/icon.png AppDir/usr/share/icons/hicolor/256x256/apps/sura.png
          
          # Create Desktop file
          cat <<EOF > AppDir/usr/share/applications/sura.desktop
          [Desktop Entry]
          Name=Sura
          Exec=sura %F
          Icon=sura
          Type=Application
          Categories=Graphics;
          EOF
          
          # Build AppImage (using -unsupported-allow-new-glibc since we run on Ubuntu 20.04 instead of 16.04)
          export VERSION=$(git describe --tags --always || echo "latest")
          ./linuxdeployqt-continuous-x86_64.AppImage AppDir/usr/share/applications/sura.desktop -appimage -unsupported-allow-new-glibc
          
      - name: Upload AppImage Artifact
        uses: actions/upload-artifact@v7
        with:
          name: Sura-AppImage
          path: Sura-*.AppImage
