name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
    
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: Sura-AppImage
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: Sura-*.AppImage
          generate_release_notes: true

      - name: Keep only 2 most recent tags and releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAGS=$(git tag -l 'v*' | sort -rV)
          mapfile -t TAG_ARRAY <<< "$TAGS"
          
          if [ ${#TAG_ARRAY[@]} -gt 2 ]; then
            for (( i=2; i<${#TAG_ARRAY[@]}; i++ )); do
              TAG_TO_DELETE="${TAG_ARRAY[$i]}"
              echo "Deleting old tag and release: $TAG_TO_DELETE"
              gh release delete "$TAG_TO_DELETE" -y || true
              git push origin --delete "$TAG_TO_DELETE" || true
            done
          else
            echo "2 or fewer tags found, nothing to delete."
          fi
